name: 'Build Docs'
description: 'Build documentation'
author: 'weierophinney'
runs:
    using: 'docker'
    image: 'Dockerfile'
inputs:
    emptyCommits:
        description: 'If empty commits should be made to the documentation'
        required: false
        default: 'true'
    username:
        description: 'Set git user.name'
        required: false
        default: 'false'
    useremail:
        description: 'Set git user.email'
        required: false
        default: 'false'
    publishDir:
        description: 'Subdirectory in which to build documentation, and subsequently publish; defaults to docs/html'
        required: false
        default: 'docs/html'
    siteUrl:
        description: 'Base URL for site containing documentation; defaults to determining from repository organization.'
        required: false
        default: ''
